owner: haochenpan
repo: diaspora-uptime-monitor

sites:
  - name: Diaspora Web Service
    url: https://diaspora-web-service.qpp943wkvr7b2.us-east-1.cs.amazonlightsail.com/
    icon: assets/octopus.png
  - name: Diaspora Action Provider
    url: https://diaspora-action-provider.qpp943wkvr7b2.us-east-1.cs.amazonlightsail.com/
    icon: assets/octopus.png
  - name: Diaspora Kafka Console
    url: http://184.73.61.163/
    icon: assets/kafka-ui.png
  # - name: Diaspora Grafana Console
    # url: http://100.29.137.186/
    # icon: assets/grafana.png

# octopus icon: https://www.flaticon.com/free-icons/octopus

assignees:
  - haochenpan

status-website:
  baseUrl: /diaspora-uptime-monitor # where "repo" is your repository name
  name: Diaspora Uptime Monitor

  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages.
  favicon: assets/octopus.png

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 * * * *"
  updates: "0 * * * *"
  uptime: "*/10 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
