owner: Diaspora
repo: diaspora-uptime-monitor

sites:
  - name: Diaspora Web Service
    url: http://3.220.110.101/
    icon: assets/octopus.png

  - name: Diaspora Action Provider
    url: https://flask-service.ml22sevubfnks.us-east-1.cs.amazonlightsail.com/
    icon: assets/octopus.png

  - name: Diaspora Admin Console
    url: http://100.27.155.7/
    icon: assets/octopus.png

# octopus icon: https://www.flaticon.com/free-icons/octopus

assignees:
  - haochenpan

status-website:
  baseUrl: /diaspora-uptime-monitor # where "repo" is your repository name
  name: Diaspora Uptime Monitor
  theme: ocean

  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages.
  favicon: assets/octopus.png

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
